# Generated by Django 5.2.1 on 2025-06-05 21:22

import chats.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', chats.models.UserManager()),
            ],
        ),
    ]
