# Generated by Django 5.2.4 on 2025-07-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_user_is_admin_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Bio"
            ),
        ),
    ]
